DELETE http://localhost:3001/api/notes/2
###
GET http://localhost:3001/api/notes/
###   
GET http://localhost:3001/api/notes/1
###
POST http://localhost:3001/api/notes
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InByaXlhX3JhaTMzIiwiaWQiOiI2OWE3ZDBhM2MwMjFiNDU1YmEyMGZhNmIiLCJpYXQiOjE3NzMzODc3NTcsImV4cCI6MTc3MzM4Nzc4N30.dFXDZWtfbRSeBILcxcq9-mBQSg8EGUbYhXcFiy2JZC4

{
    "content": "another sample1",
    "important": false
}

### GET all users
GET http://localhost:3001/api/users
###

# GET a single user by ID (replace <id> with real MongoDB ID)
GET http://localhost:3001/api/users
###

# CREATE new user
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "riya_rai2",
    "name": "riya Rai",
    "password": "123456"
}

### login
POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "priya_rai33",
  "password": "123456"
}

